In [141]:
import numpy as np 
import math
import itertools #для декартого произведения
import random

M = 512
N = 256
it_number = 100 #iteration number
prob = .35 #доля живых ~ prob

f1 = open("Life.txt", 'w')

def random_Matrix():
    Field = np.random.random((M, N)) < prob
    return Field.astype(int)

def rule(x):
    if x[0] == 1:
        if x[1] < 2 or x[1] > 3:
            return 0 #умирает
    elif x[1] == 3:
        return 1 #рождается
    return x[0]

def rollx2(x, y):
    x = np.roll(x, y[0], 0)
    x = np.roll(x, y[1], 1)
    #print x
    #print '\n'
    return x.ravel()    

def iterate(Field): #Периодические граничные условия ("сшиваем" границы)
    Field_mod = Field.copy().astype(int) #Field_mod is integer
    neibhs = np.array([[-1,-1], [-1,0], [-1,1], [0,-1], [0,1], [1,-1], [1,0], [1,1]]) #[axis0_step, axis1_step]
    
    #к каждому элементу neibhs применяем rollx2 (2 разных roll), который роллит Field. 
    #Затем (на выходе) суммируем постолбцово результат выполнения внутреннего apply_along_axis.
    #Получаем массив MxN с количеством соседей для соответствующей клетки
    neibh_count = np.apply_along_axis(np.sum, 0,\
                  np.apply_along_axis(lambda y: x8_roll(Field_mod, y), 1, neibh)).reshape((M, N))
    Field_mod = np.array(map(rule, zip(Field.ravel(), neibh_count.ravel()))).reshape(M, N)
    return Field_mod


def print_field(Field):
    print '* ' * (N+1) + '*'
    for i in range(M):
        print '*',
        for j in range(N):
            if Field[i][j] == 1:
                print 'O',
            else:
                print unicode(r'\u00B7', 'unicode-escape'),
        print '*'
    print '* ' * (N+1) + '*'  
    
def file_print_field(Field):
    f1.write('$' * (N+1) + '$\n')
    for i in range(M):
        f1.write('$')
        for j in range(N):
            if Field[i][j] == 1:
                f1.write('O')
            else:
                f1.write('*')
        f1.write('$\n')        
    f1.write('$' * (N+1) + '$\n')

In [142]:
Field = random_Matrix()
#print_field(Field)

for i in range(it_number):
    Field = iterate(Field)
    #print_field(Field)
    #file_print_field(Field)

f1.close()

In [55]:
def x8_roll(x, y):
    x = np.roll(x, y[0], 0)
    x = np.roll(x, y[1], 1)
    #print x
    #print '\n'
    return x.ravel()

    
#neibh = np.array([[0,-1], [1,-1], [0,1], [0,1], [1,1], [1,1], [0,-1], [0,-1]]) #[axis, step] roll: up, left, down , down...
neibh = np.array([[-1,-1], [-1,0], [-1,1], [0,-1], [0,1], [1,-1], [1,0], [1,1]]) #[axis0_step, axis1_step]
x = np.arange(16).reshape((4, 4))
print x
print '\n'



neibh_count = np.apply_along_axis(np.sum, 0, np.apply_along_axis(lambda y: x8_roll(x, y), 1, neibh)).reshape((4, 4))
print neibh_count

arr = np.array([True, False, True])
b = arr.astype(int)
print b
c = zip(arr, b)
print c[0][1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[60 56 64 60]
 [44 40 48 44]
 [76 72 80 76]
 [60 56 64 60]]
[1 0 1]
1
